monolog:
    channels:
        - deprecation
        - request
        - business
        - security

when@dev:
    monolog:

        handlers:

            main:
                type: stream
                path: "%kernel.logs_dir%/dev.log"
                level: debug
                channels:
                    - "!event"
                    - "!doctrine"
                    - "!security"
                    - "!request"
                    - "!http_client"
                    - "!deprecation"

            doctrine:
                type: stream
                path: "%kernel.logs_dir%/doctrine.log"
                level: debug
                channels: [doctrine]

            http:
                type: stream
                path: "%kernel.logs_dir%/http.log"
                level: info
                channels: [http_client]

            deprecation:
                type: stream
                path: "%kernel.logs_dir%/deprecation.log"
                channels: [deprecation]
                
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]                

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:

        handlers:

            main:
                type: fingers_crossed
                action_level: error
                handler: buffered
                excluded_http_codes: [400, 401, 403, 404]

            buffered:
                type: buffer
                handler: file_log
                buffer_size: 50
                flush_on_overflow: true

            file_log:
                type: stream
                path: "%kernel.logs_dir%/prod.log"
                level: debug
                formatter: monolog.formatter.json

            deprecation:
                type: stream
                path: "%kernel.logs_dir%/deprecations.log"
                channels: [deprecation]

            security:
                type: stream
                path: "%kernel.logs_dir%/security.log"
                level: warning
                channels: [security]
