nelmio_cors:
      defaults:
          allow_origin: ['*']
          allow_methods: ['GET', 'POST', 'OPTIONS']
      paths:
        '^/api/':
          allow_origin: ['*']
          allow_methods: ['GET', 'POST', 'OPTIONS']