<?php

namespace App\Controller\CredentialHub\Vault\Delete;

use App\Attribute\ExtensionAuthRequired;
use App\Attribute\PublicRoute;
use App\Controller\Shared\AbstractBackendForwardingController;
use App\Service\Shared\ProcessKey;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\User\BackendForwardingService;
use Symfony\Component\HttpFoundation\JsonResponse;
use Psr\Log\LoggerInterface;

/**
 * Vault delete flow:
 * 1. Generate a QR code for vault deletion (basically sessionId generation). => State, and temporary data(basically state and sessionId~processId)
 * saved in the AuthBridge table by the API.
 * 2. Read the QR code with the mobile application.
 * 3. Call the /credential endpoint for confirmation and deletion execution.
 * -- the process deletes the credential for the current vault directly from the table,
 * but the state is available only in the temporary table(auth_bridge).
 * 4. Use the /state endpoint to deliver the process status.
 *
 * Generally: The deletion requests from the mobile app are sent to the backend API only for direct execution.
 * The state endpoint is used to check the process status and confirm deletion, after which the temporary data is removed.
 */
#[Route('/api/credential-hub/vault/delete')]
class VaultDeleteController extends AbstractBackendForwardingController
{
    public function __construct(
        private LoggerInterface $logger
    ) {
    }

    /*
     * Called by Browser-Extension
    */
    #[PublicRoute('Public Credential Hub bootstrap route that creates the vault-delete process and returns the initial QR/session payload.')]
    #[Route('/qr-identity', name: ProcessKey::VAULT_DELETE_QR_IDENTITY, methods: "POST")]
    public function vaultDeleteQrIdentity(
        Request $request,
        BackendForwardingService $backendForwardingService
    ): JsonResponse {
        return $this->forwardProcessRequest($request, $backendForwardingService, $this->logger, ProcessKey::VAULT_DELETE_QR_IDENTITY);
    }

    /*
     * API endpoint for vault deletion confirmation (called by Mobile App).
     * The QR code generated by the first method is scanned by the mobile app, which sends a confirmation to this endpoint.
     * This endpoint forwards the confirmation request to the backend API for execution.
     * Backend response is decoded and returned as JSON.
     */
    #[ExtensionAuthRequired('Vault-delete confirmation must include the X-Extension-Auth header established by the bootstrap step.')]
    #[Route('/credential', name: ProcessKey::VAULT_DELETE_CREDENTIAL, methods: "POST")]
    public function vaultDeleteCredential(
        Request $request,
        BackendForwardingService $backendForwardingService
    ): JsonResponse {
        return $this->forwardProcessRequest($request, $backendForwardingService, $this->logger, ProcessKey::VAULT_DELETE_CREDENTIAL);
    }

    /**
     * API endpoint for vault deletion state polling (called by Browser-Extension).
     * Receives state request data and extension auth header, forwards securely to backend.
     * Backend response is decoded and returned as JSON.
     */
    #[ExtensionAuthRequired('Vault-delete state polling must include the X-Extension-Auth header established by the bootstrap step.')]
    #[Route('/state', name: ProcessKey::VAULT_DELETE_STATE, methods: "POST")]
    public function vaultDeleteState(
        BackendForwardingService $backendForwardingService,
        Request $request
    ): JsonResponse {
        return $this->forwardProcessRequest($request, $backendForwardingService, $this->logger, ProcessKey::VAULT_DELETE_STATE);
    }
}
