<?php

/**
 * Flow overview:
 * 1. Browser extension requests QR identity with the adjusted credentials
 * 2. Mobile App scans QR →  encrypt credentials and send confirmation back to the API
 * 3. Browser extension polls state → receives backend processing status.
 *
 * Important behavior:
 * - Vault edit is implemented as DELETE + CREATE (no direct update).
 * - All requests are forwarded to the backend API through the backend forwarding service.
 * - Payloads are encrypted before forwarding.
 * - Backend responses are decoded and returned as JSON.
 */

namespace App\Controller\CredentialHub\Vault\Edit;

use App\Attribute\ExtensionAuthRequired;
use App\Attribute\PublicRoute;
use App\Controller\Shared\AbstractBackendForwardingController;
use App\Service\Shared\ProcessKey;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\User\BackendForwardingService;
use Symfony\Component\HttpFoundation\JsonResponse;
use Psr\Log\LoggerInterface;

#[Route('/api/credential-hub/vault/edit')]
class VaultEditController extends AbstractBackendForwardingController
{
    public function __construct(
        private LoggerInterface $logger
    ) {
    }

    /*
     * The QR code currently included the user credentials in encrypted form
     * Vault update and registration is the same process. We do not make any update. Delete and create new
     */
    #[PublicRoute('Public Credential Hub bootstrap route that creates the vault-edit process and returns the initial QR/session payload.')]
    #[Route('/qr-identity', name: ProcessKey::VAULT_EDIT_QR_IDENTITY, methods: "POST")]
    public function vaultEditQrIdentity(
        Request $request,
        BackendForwardingService $backendForwardingService
    ): JsonResponse {
        return $this->forwardProcessRequest($request, $backendForwardingService, $this->logger, ProcessKey::VAULT_EDIT_QR_IDENTITY);
    }

    /*
     * API endpoint for vault edit confirmation (called by Mobile App).
     * The QR code generated by the first method is scanned by the mobile app, which sends a confirmation to this endpoint.
     * The credentials encrypted by the mobile app are sent to this endpoint, which forwards them to the backend API for execution.
     * Backend response is decoded and returned as JSON.
     */
    #[ExtensionAuthRequired('Vault-edit credential submission must include the X-Extension-Auth header established by the bootstrap step.')]
    #[Route('/credential', name: ProcessKey::VAULT_EDIT_CREDENTIAL, methods: "POST")]
    public function vaultEditCredential(
        Request $request,
        BackendForwardingService $backendForwardingService
    ): JsonResponse {
        return $this->forwardProcessRequest($request, $backendForwardingService, $this->logger, ProcessKey::VAULT_EDIT_CREDENTIAL);
    }

    /*
     * API endpoint for vault edit state polling (called by Browser-Extension).
     * Receives state request data and extension auth header, forwards to backend API.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[ExtensionAuthRequired('Vault-edit state polling must include the X-Extension-Auth header established by the bootstrap step.')]
    #[Route('/state', name: ProcessKey::VAULT_EDIT_STATE, methods: "POST")]
    public function vaultEditState(
        BackendForwardingService $backendForwardingService,
        Request $request
    ): JsonResponse {
        return $this->forwardProcessRequest($request, $backendForwardingService, $this->logger, ProcessKey::VAULT_EDIT_STATE);
    }
}
