<?php
/**
 * Flow overview:
 * 1. Browser extension requests QR identity with the adjusted credentials
 * 2. Mobile App scans QR →  encrypt credentials and send confirmation back to the API
 * 3. Browser extension polls state → receives backend processing status.
 *
 * Important behavior:
 * - Vault edit is implemented as DELETE + CREATE (no direct update).
 * - All requests are forwarded to the backend API through UserRegistrationService.
 * - Payloads are encrypted before forwarding.
 * - Backend responses are decoded and returned as JSON.
 */
namespace App\Controller\CredentialHub\Vault\Edit;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\User\UserRegistrationService;
use Symfony\Component\HttpFoundation\JsonResponse;
use Psr\Log\LoggerInterface;
use App\Controller\CredentialHub\BackendForwared;


#[Route('/api/credential-hub/vault/edit')]
class VaultEditController extends AbstractController
{
    public function __construct(
        private LoggerInterface $logger
    ) {}

    /*
     * The QR code currently included the user credentials in encrypted form    
     * Vault update and registration is the same process. We do not make any update. Delete and create new
     */
    #[Route('/qr-identity', name: 'vault_edit_qr_identity', methods: "POST")]
    public function vaultEditQrIdentity(
        Request $request,
        UserRegistrationService $userRegistrationService
    ): JsonResponse {
        return BackendForwared::forward($request, $userRegistrationService, $this->logger, 'vault_edit_qr_identity');
    }

    /*
     * API endpoint for vault edit confirmation (called by Mobile App).
     * The QR code generated by the first method is scanned by the mobile app, which sends a confirmation to this endpoint.
     * The credentials encrypted by the mobile app are sent to this endpoint, which forwards them to the backend API for execution.
     * Uses UserRegistrationService->forwardRegistration, which encrypts and sends data to backend API.
     * Backend response is decoded and returned as JSON.
     */
    #[Route('/credential', name: 'vault_edit_credential', methods: "POST")]
    public function vaultEditCredential(
        Request $request,
        UserRegistrationService $userRegistrationService
    ): JsonResponse {
        return BackendForwared::forward($request, $userRegistrationService, $this->logger, 'vault_edit_credential', true);
    }    

    /*
     * API endpoint for vault edit state polling (called by Browser-Extension).
     * Receives state request data and extension auth header, forwards to backend API.
     * Uses UserRegistrationService->forwardRegistration, which encrypts and sends data to backend API.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[Route('/state', name: 'vault_edit_state', methods: "POST")]
    public function vaultEditState(
        UserRegistrationService $userRegistrationService,
        Request $request
    ): JsonResponse {
        return BackendForwared::forward($request, $userRegistrationService, $this->logger, 'vault_edit_state', true);
    }    
}
