<?php

/**
 * Handles user registration workflows via the HUB frontend.
 *
 * Responsibilities:
 * - Delegates view-data preparation to RegistrationService.
 * - Renders the registration page with QR code and availability state.
 */

namespace App\Controller\User\Registration\HUB;

use App\Attribute\PublicRoute;
use App\Service\User\Registration\HUB\RegistrationService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class RegistrationController extends AbstractController
{
    /*
     * Renders the user registration page with a QR code for the registration process.
     * The QR code is generated by the RegistrationService and is used to initiate the user registration process.
     */
    #[PublicRoute('Public user registration page used to bootstrap the HUB browser registration flow.')]
    #[Route('/user-registration', name: 'user-registration', methods: "GET")]
    public function userRegistration(Request $request, RegistrationService $registrationService): Response
    {
        $viewData = $registrationService->buildRegistrationViewData($request);

        return $this->render('views/users/user-registration.html.twig', $viewData->toArray());
    }
}
