<?php
/**
 * Handles user registration workflows via the HUB frontend.
 *
 * Responsibilities:
 * - Renders the user registration page and generates a QR code for the registration process using UserService.
 * - Uses UserRegistrationService->forwardRegistration, which encrypts and sends data to backend API.
 * - Supports frontend instance registration menu visibility.
 */
namespace App\Controller\User\Registration\HUB;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Controller\User\UserService;
use Psr\Log\LoggerInterface;

class RegistrationController extends AbstractController
{
    public function __construct(
        private LoggerInterface $logger,
        private UserService $userService
    ) {}

    /*
     * Renders the user registration page with a QR code for the registration process.
     * The QR code is generated by the UserService and is used to initiate the user registration process.
     */
    #[Route('/user-registration', name: 'user-registration', methods: "GET")]
    public function userRegistration() 
    {
        $process = "user_registration"; 

        return $this->render('views/users/user-registration.html.twig', [
            'qrCode' => $this->userService->getQrCode($process, []),
            'menuItem_instanceRegistration' => true
        ]);
    }
}
