<?php

/**
 * API login flow.
 * 1. Generate login QR code for HUB frontend or any other Integrated domain.
 * HUB Frontend:
 * 2. /api/user-login/callback => Used by the HUB frontend to receive login confirmations on the database level.
 * 3. /api/user-login/new-qr => Used by the HUB Frontend to generate a new QR code for login.
 * 4. /api/user-login/check => Used by the HUB Frontend to poll the login status after the QR code has been scanned.
 */

namespace App\Controller\User\Login\Api;

use App\Attribute\CsrfProtectedRoute;
use App\Attribute\PublicRoute;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\DTO\QrCodeResponseDTO;
use Psr\Log\LoggerInterface;
use App\Service\JWT\JwtService;
use App\Service\Shared\ProcessKey;
use App\Service\User\Callback\UserProcessCallbackService;
use App\Service\User\Login\Api\LoginApiRequestMapper;
use App\Service\User\UserQrCodeService;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Csrf\CsrfTokenManagerInterface;
use App\Repository\UserRepository;
use App\Service\Security\ApiRateLimitService;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Security\Core\User\UserInterface;

class LoginController extends AbstractController
{
    public function __construct(
        private LoggerInterface $logger,
        private UserQrCodeService $userQrCodeService,
        private UserProcessCallbackService $userProcessCallbackService,
        private JwtService $jwtService,
        private LoginApiRequestMapper $loginApiRequestMapper,
        private ApiRateLimitService $apiRateLimitService,
    ) {
    }

    /*
    * API endpoint called from any registered domain to generate a QR code for login.
    * Not for HUB Frontend, but for any other domain that wants to use the login functionality.
    */
    #[PublicRoute('Public API route that starts the login QR flow; protected by payload validation and rate limiting.')]
    #[Route('/api/user-login', name: 'api_instance_login', methods: "POST")]
    public function apiLogin(
        Request $request
    ): JsonResponse {
        if (($rateLimitedResponse = $this->apiRateLimitService->assertApiUserLoginAllowed($request)) !== null) {
            return $rateLimitedResponse;
        }

        $corporateIdentification = $this->loginApiRequestMapper->mapLoginRequest($request);

        $response = $this->userQrCodeService->getQrCode(ProcessKey::USER_LOGIN, $corporateIdentification, $corporateIdentification->userPublicId);

        return new JsonResponse($response->toArray());
    }

    /*
     * API endpoint for user login callback (called by the API after Mobile App confirmation).
    * Used only by the HUB frontend to receive login confirmations on the database level.
     * The QR code generated by the first method is scanned by the mobile app, which sends a confirmation to API,
     * and the API forwards it to this endpoint.
        * If this endpoint receives the callback, it allows the user to log in to the system, because it
     * sets the flag in the database on the API side
     *
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[PublicRoute('Public API callback endpoint for login confirmations; protected by callback-specific validation and rate limiting.')]
    #[Route('/api/user-login/callback', name: 'user_login_callback', methods: ["POST"])]
    public function systemHubLoginCallback(
        Request $request
    ): JsonResponse {
        if (($rateLimitedResponse = $this->apiRateLimitService->assertApiUserLoginCallbackAllowed($request)) !== null) {
            return $rateLimitedResponse;
        }

        $response = $this->loginApiRequestMapper->mapCallbackRequest($request);

        return new JsonResponse([
            'status' => 'ok',
            'success' => $this->userProcessCallbackService->allowLoginProcess($response),
        ]);
    }

    /*
    * API endpoint called from the HUB Frontend to generate a new QR code for login.
    * CSRF is not primary protection, but extra browser-level guard
    */
    #[PublicRoute('Public API route for refreshing login QR codes; protected by CSRF and rate limiting.')]
    #[CsrfProtectedRoute('Mutating login QR refresh route requires a valid CSRF token in the X-CSRF-TOKEN header.', tokenId: 'userLoginCsrf', tokenField: 'X-CSRF-TOKEN', tokenSource: 'header', failureMessage: 'Invalid CSRF token')]
    #[Route('/api/user-login/new-qr', name: 'user_login_new_qr', methods: "POST")]
    public function userLoginNewQr(
        Request $request,
        CsrfTokenManagerInterface $csrfTokenManager
    ): JsonResponse {
        if (($rateLimitedResponse = $this->apiRateLimitService->assertApiUserLoginNewQrAllowed($request)) !== null) {
            return $rateLimitedResponse;
        }

        $token = $csrfTokenManager->getToken('userLoginCsrf')->getValue();

        // For future: use for "OneTouch" login
        $userPublicId = null;

        return new JsonResponse([
            'authentication' => $this->userQrCodeService->getQrCode(ProcessKey::USER_LOGIN, null, $userPublicId)->toArray(),
            'userLoginCsrf' => $token
        ]);
    }

    /*
        * Legacy API endpoint kept for compatibility.
        * API endpoint called by the HUB frontend to poll the login status after the QR code has been scanned.
    * Validates the CSRF token and checks if the user associated with the login process is allowed to log in.
    * If allowed, generates a JWT token for the user and returns it in the response, along with setting a secure, HTTP-only cookie for the JWT token.
     * If not allowed, returns an error message indicating unsuccessful authentication.
     * The QR code validity period is 10 seconds, after which the login attempt will fail if not completed.
     * CSRF is not primary protection, but extra browser-level guard
    */
    #[PublicRoute('Public API polling endpoint for login completion; protected by CSRF, payload validation, and rate limiting.')]
    #[CsrfProtectedRoute('Polling route requires a valid CSRF token in the X-CSRF-TOKEN header.', tokenId: 'userLoginCsrf', tokenField: 'X-CSRF-TOKEN', tokenSource: 'header', failureMessage: 'Invalid CSRF token')]
    #[Route('/api/user-login/check', name: 'user_login_check', methods: "POST")]
    public function userLoginCheck(
        Request $request,
        UserRepository $userRepository
    ): JsonResponse {
        if (($rateLimitedResponse = $this->apiRateLimitService->assertApiUserLoginCheckAllowed($request)) !== null) {
            return $rateLimitedResponse;
        }

        $payload  = $this->loginApiRequestMapper->mapCheckRequest($request);

        $processId = $this->extractProcessId($payload);

        $user = $userRepository->findOneBy(['process' => $processId]);

        if (!$user || !$user->isAllowed()) {
            return $this->authenticationFailed();
        }

        return $this->authenticationSuccess($user);
    }

    private function authenticationSuccess(UserInterface $user): JsonResponse
    {
        $token = $this->jwtService->createToken($user);
        $response = new JsonResponse([
            'message' => 'Authentication success',
        ]);

        $response->headers->setCookie($this->jwtService->createCookieFromToken($token));

        return $response;
    }

    private function extractProcessId(QrCodeResponseDTO $payload): string
    {
        if ($payload->getDomainProcessId() === null) {
            throw new BadRequestHttpException('domainProcessId missing');
        }

        return (string) $payload->getDomainProcessId();
    }

    private function authenticationFailed(): JsonResponse
    {
        return new JsonResponse([
            'message' => 'Authentication failed. QR code expired.'
        ], 401);
    }
}
