<?php
/**
 * Any:
 * 1. Generate login QR code for HUB frontend or any other Integrated domain.
 * HUB Frontend:
 * 2. /api/user-login/callback => Used by the HUB Frontend to receive login confirmations.=> Only on the Database level
 * 3. /api/user-login/new-qr => Used by the HUB Frontend to generate a new QR code for login.
 * 4. /api/user-login/check => Used by the HUB Frontend to poll the login status after the QR code has been scanned.
 */
namespace App\Controller\User\Login\Api;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Controller\User\UserService;
use Psr\Log\LoggerInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Csrf\CsrfTokenManagerInterface;
use Symfony\Component\Security\Csrf\CsrfToken;
use App\Repository\UserRepository;
use Lexik\Bundle\JWTAuthenticationBundle\Services\JWTTokenManagerInterface;
use App\DTO\RegistrationProcessDTO;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;

class LoginController extends AbstractController
{
    public function __construct(
        private LoggerInterface $logger,
        private UserService $userService
    ) {}

    /*
    * API endpoint called from any registered domain to generate a QR code for login.
    * Not for HUB Frontend, but for any other domain that wants to use the login functionality.
    */
    #[Route('/api/user-login', name: 'api_instance_login', methods: "POST")]
    public function apiLogin(
        Request $request
    ) {   
        $corporateIentification = $this->decodeRequest($request);
        $response = $this->userService->getQrCode('user_login', $corporateIentification, $corporateIentification['userPublicId'] ?? null);
        return $this->json($response);
    }    

    /*
     * API endpoint for user login callback (called by the API after Mobile App confirmation).
     * Used only by the HUB Frontend to receive login confirmations.=> Only on the Database level
     * The QR code generated by the first method is scanned by the mobile app, which sends a confirmation to API, 
     * and the API forwards it to this endpoint.
     * If this endpoint receives the callback, it allowes the user to log in the system, because it
     * sets the flag in the database on the API side
     * 
     * Uses UserRegistrationService->forwardRegistration, which encrypts and sends data to backend API.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[Route('/api/user-login/callback', name: 'user_login_callback', methods: ["POST"])]
    public function systemHubLoginCallback(
        Request $request
        ): JsonResponse
    {
        $response = $this->decodeRequest($request);
        $dto = RegistrationProcessDTO::mapFromArrayLogin($response);

        return new JsonResponse([
            'status' => 'ok',
            'success' => $this->userService->allowSetUserLoginProcess($dto),
        ]);
    }
    
    /*
    * API endpoint called from the HUB Frontend to generate a new QR code for login.
    * CSRF is not primary protection, but extra browser-level guard
    */
    #[Route('/api/user-login/new-qr', name: 'user_login_new_qr', methods: "POST")]
    public function userLoginNewQr(
        Request $request,
        CsrfTokenManagerInterface $csrfTokenManager
        ) {  

        $tokenFromHeader = $request->headers->get('X-CSRF-TOKEN');
        $token = $csrfTokenManager->getToken('userLoginCsrf')->getValue();

        if (!$csrfTokenManager->isTokenValid(new CsrfToken('userLoginCsrf', $tokenFromHeader))) {
            return new JsonResponse(['error' => 'Invalid CSRF token'], 403);
        }

        // For future: use for "OneTouch" login
        $userPublicId = "";

        return $this->json([
            'authentication' => $this->userService->getQrCode('user_login', [], $userPublicId),
            'userLoginCsrf' => $token
        ]);
    }

    /*
    * Not USED => Has to be checked
    * API endpoint called from the HUB ??? Frontend to poll the login status after the QR code has been scanned.
    * Validates the CSRF token and checks if the user associated with the login process is allowed to log in.
    * If allowed, generates a JWT token for the user and returns it in the response, along with setting a secure, HTTP-only cookie for the JWT token.
     * If not allowed, returns an error message indicating unsuccessful authentication.
     * The QR code validity period is 10 seconds, after which the login attempt will fail if not completed.
     * CSRF is not primary protection, but extra browser-level guard
    */
    #[Route('/api/user-login/check', name: 'user_login_check', methods: "POST")]
    public function userLoginCheck(
        Request $request,
        CsrfTokenManagerInterface $csrfTokenManager,
        UserRepository $userRepository,
        JWTTokenManagerInterface $jwtManager
    ): JsonResponse
    {
        $this->assertValidCsrf($request, $csrfTokenManager);

        $payload  = $this->decodeRequest($request);
        $processId = $this->extractProcessId($payload );

        $user = $userRepository->findOneByProcess($processId);

        if (!$user || !$user->isAllowed()) {
            return $this->authenticationFailed();
        }

        $token = $jwtManager->create($user);
        return $this->authenticationSuccess($token);
    }
    
    private function authenticationSuccess(string $token): JsonResponse
    {
        $response = new JsonResponse([
            'message' => 'Authentication success',
            'jwt_token' => $token,
        ]);

        $response->headers->setCookie(
            $this->buildJwtCookie($token)
        );

        return $response;
    }    

    private function assertValidCsrf(
        Request $request,
        CsrfTokenManagerInterface $csrfTokenManager
    ) {
        $token = $request->headers->get('X-CSRF-TOKEN');
        if (!$csrfTokenManager->isTokenValid(
            new CsrfToken('userLoginCsrf', $token)
        )) {
            throw new AccessDeniedHttpException('Invalid CSRF token');
        }
    }

    private function extractProcessId(array $payload): string
    {
        if (empty($payload['domainProcessId'])) {
            throw new BadRequestHttpException('domainProcessId missing');
        }

        return $payload['domainProcessId'];
    }

    private function authenticationFailed(): JsonResponse
    {
        return new JsonResponse([
            'message' => 'Authentication failed. QR code expired.'
        ], 401);
    }

    private function decodeRequest(Request $request): array
    {
        try {
            return json_decode(
                $request->getContent(),
                true,
                512,
                JSON_THROW_ON_ERROR
            );
        } catch (\JsonException $e) {
            $this->logger->error('Invalid login callback JSON', [
                'error' => $e->getMessage(),
            ]);

            throw new BadRequestHttpException('Invalid JSON payload');
        }
    }   
}
