<?php

namespace App\Controller\CredentialHub\Domain\Delete;

use App\Attribute\ExtensionAuthRequired;
use App\Attribute\PublicRoute;
use App\Controller\Shared\AbstractBackendForwardingController;
use App\Service\Shared\ProcessKey;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\User\BackendForwardingService;
use Symfony\Component\HttpFoundation\JsonResponse;
use Psr\Log\LoggerInterface;

/**
 * Domain delete flow:
 * 1. Generate a QR code for domain deletion (basically sessionId generation).
 *      => State, and temporary data(basically state and sessionId~processId) saved in the AuthBridge table by the API.
 * 2. Read the QR code with the mobile application. => this is the confirmation step
 * 3. Mobile call the /credential endpoint for deletion execution.
 * -- the process deletes the credential for the current domain directly from the table,
 * but the state is available only in the temporary table(auth_bridge).
 * 4. Use the /state endpoint to deliver the process status.
 *
 * Generally: The deletion requests from the mobile app are sent to the backend API only for direct execution.
 * The state endpoint is used to check the process status and confirm deletion, after which the temporary data is removed.
 */
#[Route('/api/credential-hub/domain/delete')]
class DomainDeleteController extends AbstractBackendForwardingController
{
    public function __construct(
        private LoggerInterface $logger
    ) {
    }

    /*
        * API endpoint for QR-based domain deletion (called by Browser-Extension).
        * Receives QR identity data, forwards it to the Browser-Extension. Only initial step to get the sessionId.
        * Calls the backend forwarding service, which encrypts and forwards data to backend API.
        * Backend response is decoded and returned as JSON.
        */
    #[PublicRoute('Public Credential Hub bootstrap route that creates the domain-delete process and returns the initial QR/session payload.')]
    #[Route('/qr-identity', name: ProcessKey::DOMAIN_DELETE_QR_IDENTITY, methods: ["POST"])]
    public function domainDeleteQrIdentity(
        Request $request,
        BackendForwardingService $backendForwardingService
    ): JsonResponse {
        return $this->forwardProcessRequest($request, $backendForwardingService, $this->logger, ProcessKey::DOMAIN_DELETE_QR_IDENTITY);
    }

    /*
     * API endpoint for domain deletion confirmation (called by Mobile App).
     * The QR code generated by the first method is scanned by the mobile app, which sends a confirmation to this endpoint.
     * This endpoint forwards the confirmation request to the backend API for execution(delete the credential).
     * Backend response is decoded and returned as JSON.
     */
    #[ExtensionAuthRequired('Domain-delete confirmation must include the X-Extension-Auth header established by the bootstrap step.')]
    #[Route('/credential', name: ProcessKey::DOMAIN_DELETE_CREDENTIAL, methods: ["POST"])]
    public function domainDeleteCredential(
        Request $request,
        BackendForwardingService $backendForwardingService
    ): JsonResponse {
        return $this->forwardProcessRequest($request, $backendForwardingService, $this->logger, ProcessKey::DOMAIN_DELETE_CREDENTIAL);
    }

    /**
     * API endpoint for domain deletion state polling (called by Browser-Extension).
     * Receives state request data and extension auth header, forwards securely to backend.
     * Backend response is decoded and returned as JSON.
     */
    #[ExtensionAuthRequired('Domain-delete state polling must include the X-Extension-Auth header established by the bootstrap step.')]
    #[Route('/state', name: ProcessKey::DOMAIN_DELETE_STATE, methods: ["POST"])]
    public function domainDeleteState(
        Request $request,
        BackendForwardingService $backendForwardingService
    ): JsonResponse {
        return $this->forwardProcessRequest($request, $backendForwardingService, $this->logger, ProcessKey::DOMAIN_DELETE_STATE);
    }
}
