<?php

namespace App\Controller\CredentialHub\Domain\Delete;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\User\UserRegistrationService;
use Symfony\Component\HttpFoundation\JsonResponse;
use Psr\Log\LoggerInterface;


/**
 * Domain delete flow:
 * 1. Generate a QR code for domain deletion (basically sessionId generation). => State, and temporary data(basically state and sessionId~processId)
 * saved in the AuthBridge table by the API.
 * 2. Read the QR code with the mobile application.
 * 3. Call the /credential endpoint for confirmation and deletion execution.
 * -- the process deletes the credential for the current domain directly from the table,
 * but the state is available only in the temporary table(auth_bridge).
 * 4. Use the /state endpoint to deliver the process status.
 *
 * Generally: The deletion requests from the mobile app are sent to the backend API only for direct execution. 
 * The state endpoint is used to check the process status and confirm deletion, after which the temporary data is removed.
 */
#[Route('/api/credential-hub/domain/delete')]
class DomainDeleteController extends AbstractController
{
    public function __construct(
        private LoggerInterface $logger
    ) {}

    /*
     * API endpoint for QR-based domain deletion (called by Browser-Extension).
     * Receives QR identity data, forwards it to the Browser-Extension. Only initial step to get the sessionId.
     * Calls UserRegistrationService->forwardRegistration, which encrypts and forwards data to backend API.
     * Backend response is decoded and returned as JSON.
     */
    #[Route('/qr-identity', name: 'domain_delete_qr_identity', methods: "POST")]
    public function domainDeleteQrIdentity(
        Request $request,
        UserRegistrationService $userRegistrationService
    ): JsonResponse {
        $contentJson = $request->getContent();
        $process = "domain_delete_qr_identity";

        /** @var Response $response */
        $response = $userRegistrationService->forwardRegistration(
            [
                $process => $contentJson
            ]
        );
        
        $content = $response->getContent();
        $decodedJson = \json_decode($content);

        return $this->json($decodedJson);
    }

    /*
     * API endpoint for domain deletion confirmation (called by Mobile App).
     * The QR code generated by the first method is scanned by the mobile app, which sends a confirmation to this endpoint.
     * This endpoint forwards the confirmation request to the backend API for execution.
     * Uses UserRegistrationService->forwardRegistration, which encrypts and sends data to backend API.
     * Backend response is decoded and returned as JSON.
     */
    #[Route('/credential', name: 'domain_delete_credential', methods: "POST")]
    public function domainDeleteCredential(
        Request $request,
        UserRegistrationService $userRegistrationService
    ): JsonResponse {
        $contentJson = $request->getContent();
        $process = "domain_delete_credential";

        /** @var Response $response */
        $response = $userRegistrationService->forwardRegistration(
            [$process => $contentJson,
            'X-Extension-Auth' => $request->headers->get('X-Extension-Auth')]
        );

        $content = $response->getContent();
        $decodedJson = \json_decode($content);

        return $this->json($decodedJson);
    }    

    /**
     * API endpoint for domain deletion state polling (called by Browser-Extension).
     * Receives state request data and extension auth header, forwards securely to backend.
     * Uses UserRegistrationService->forwardRegistration, which encrypts and sends data to backend API.
     * Backend response is decoded and returned as JSON.
     */
    #[Route('/state', name: 'domain_delete_state', methods: "POST")]
    public function domainDeleteState(
        UserRegistrationService $userRegistrationService,
        Request $request
    ): JsonResponse {
        $contentJson = $request->getContent();
        $process = "domain_delete_state";

        /** @var Response $response */
        $response = $userRegistrationService->forwardRegistration(
            [
                $process => $contentJson,
                'X-Extension-Auth' => $request->headers->get('X-Extension-Auth')
            ]
        );

        $content = $response->getContent();
        $decodedJson = \json_decode($content);

        return $this->json($decodedJson);
    }    
}
