<?php
/**
 * Any:
 * 1. Generate registration QR code for HUB frontend or any other Integrated domain.
 * HUB Frontend:
 * 2. /api/registration/callback => Used by the HUB Frontend to receive registration confirmations.=> Only on the Database level
 */
namespace App\Controller\User\Registration\Api;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use App\Controller\User\UserService;
use Psr\Log\LoggerInterface;
use App\DTO\RegistrationProcessDTO;

class RegistrationController extends AbstractController
{
    public function __construct(
        private LoggerInterface $logger,
        private UserService $userService
    ) {}

    /*
     * API endpoint for initiating user registration (called by Any integrated external domain).
     * Receives corporate identification data, forwards it to the UserService to generate a QR code for the registration process.
     * The QR code is used to initiate the user registration process.
     * Uses UserRegistrationService->forwardRegistration, which encrypts and sends data to backend API.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[Route('/api/user-registration', name: 'api-user-registration', methods: "POST")]
    public function apiUserRegistration(        
        Request $request
        ) 
    {       
        $headers =  $request->headers->all();

        $corporateIentification = json_decode($request->getContent(), true);       

        $process = "user_registration"; 

        $corporateIentification['hmac'] = $headers['x-client-auth'];

        $response = $this->userService->getQrCode($process, $corporateIentification);

        return $this->json($response);
    }    

    /*
     * API endpoint for user registration callback (called by the API after Mobile App confirmation).
     * Used only by the HUB Frontend to receive registration confirmations.=> Only on the Database level
     * The QR code generated by the first method is scanned by the mobile app, which sends a confirmation to API, 
     * and the API forwards it to this endpoint.
     * If this endpoint receives the callback, it creates the user in the system and may also create a registration process 
     * to track the registration status.
     * 
     * Uses UserRegistrationService->forwardRegistration, which encrypts and sends data to backend API.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[Route('/api/registration/callback', name: 'user_registration_callback', methods: ["POST"])]
    public function systemHubRegistrationCallback(Request $request): JsonResponse
    {
        try {
            $response = json_decode($request->getContent(), true, 512, JSON_THROW_ON_ERROR);
            $dto = RegistrationProcessDTO::mapFromArrayRegistration($response);

            $this->userService->createUser($dto);
            // and create process !!! to check from frontend

            return new JsonResponse(['status' => 'success', 'data' => 'callback success'], Response::HTTP_OK);
        } catch (\JsonException $e) {
            return new JsonResponse([
                'status' => 'error',
                'message' => 'Invalid JSON payload: ' . $e->getMessage()
            ], Response::HTTP_BAD_REQUEST);
        } catch (\Exception $e) {
            return new JsonResponse([
                'status' => 'error',
                'message' => 'Server error: ' . $e->getMessage()
            ], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }
}
