<?php

/**
 * API registration flow.
 * 1. Generate registration QR code for HUB frontend or any other Integrated domain.
 * HUB Frontend:
 * 2. /api/registration/callback => Used by the HUB frontend to receive registration confirmations on the database level.
 */

namespace App\Controller\User\Registration\Api;

use App\Attribute\ClientAuthRequired;
use App\Attribute\PublicRoute;
use App\Logger\LogTrace;
use App\Service\Security\ApiRateLimitService;
use App\Service\Security\ClientAuthRequestResolver;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Psr\Log\LoggerInterface;
use App\Service\Shared\ProcessKey;
use App\Service\User\Registration\Api\RegistrationApiRequestMapper;
use App\Service\User\Callback\UserProcessCallbackService;
use App\Service\User\UserQrCodeService;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpFoundation\JsonResponse as HttpJsonResponse;

class RegistrationController extends AbstractController
{
    public function __construct(
        private LoggerInterface $logger,
        private UserQrCodeService $userQrCodeService,
        private UserProcessCallbackService $userProcessCallbackService,
        private RegistrationApiRequestMapper $registrationApiRequestMapper,
        private ApiRateLimitService $apiRateLimitService,
        private ?ClientAuthRequestResolver $clientAuthRequestResolver = null,
    ) {
    }

    /*
    * API endpoint for initiating user registration from any integrated external domain.
    * Receives corporate identification data and forwards it to the QR-code application service.
     * The QR code is used to initiate the user registration process.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[ClientAuthRequired]
    #[Route('/api/user-registration', name: 'api-user-registration', methods: "POST")]
    public function apiUserRegistration(
        Request $request
    ): JsonResponse {
        if (($rateLimitedResponse = $this->apiRateLimitService->assertApiUserRegistrationAllowed($request)) !== null) {
            return $rateLimitedResponse;
        }

        $hmac = ($this->clientAuthRequestResolver ??= new ClientAuthRequestResolver(new \App\Service\Security\ApiClientAuthGuard()))->resolveOrDeny($request);

        if ($hmac instanceof HttpJsonResponse) {
            return $hmac;
        }

        $corporateIdentification = $this->registrationApiRequestMapper->mapRegistrationRequest($request, $hmac);
        $response = $this->userQrCodeService->getQrCode(ProcessKey::USER_REGISTRATION, $corporateIdentification);

        return new JsonResponse($response->toArray());
    }

    /*
     * API endpoint for user registration callback (called by the API after Mobile App confirmation).
    * Used only by the HUB frontend to receive registration confirmations on the database level.
     * The QR code generated by the first method is scanned by the mobile app, which sends a confirmation to API,
     * and the API forwards it to this endpoint.
     * If this endpoint receives the callback, it creates the user in the system and may also create a registration process
     * to track the registration status.
     *
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[PublicRoute('Public API callback endpoint for registration confirmations; protected by callback-specific validation and rate limiting.')]
    #[Route('/api/registration/callback', name: 'user_registration_callback', methods: ["POST"])]
    public function systemHubRegistrationCallback(Request $request): JsonResponse
    {
        if (($rateLimitedResponse = $this->apiRateLimitService->assertApiUserRegistrationCallbackAllowed($request)) !== null) {
            return $rateLimitedResponse;
        }

        try {
            $response = $this->registrationApiRequestMapper->decodeCallbackPayload($request);
            $dto = $this->registrationApiRequestMapper->mapCallbackPayload($response);

            $this->logger->info('Registration callback payload received', [
                'payload_keys' => array_keys($response),
                'registration_process_hash' => isset($response['registrationProcessId']) && is_string($response['registrationProcessId']) ? LogTrace::fingerprint($response['registrationProcessId']) : null,
                'process_hash' => LogTrace::fingerprint($dto->getProcessId()),
                'email_hash' => isset($response['email']) && is_string($response['email']) ? LogTrace::fingerprint($response['email']) : null,
                'public_id_hash' => isset($response['publicId']) && is_string($response['publicId']) ? LogTrace::fingerprint($response['publicId']) : null,
            ]);

            $this->logger->info('Registration callback DTO mapped', [
                'email_hash' => LogTrace::fingerprint($dto->getEmail()),
                'public_id_hash' => LogTrace::fingerprint($dto->getPublicId()),
                'process_hash' => LogTrace::fingerprint($dto->getProcessId()),
            ]);

            if (!$this->userProcessCallbackService->createRegisteredUser($dto)) {
                $this->logger->warning('Registration callback rejected', [
                    'email_hash' => LogTrace::fingerprint($dto->getEmail()),
                    'public_id_hash' => LogTrace::fingerprint($dto->getPublicId()),
                    'process_hash' => LogTrace::fingerprint($dto->getProcessId()),
                ]);

                return new JsonResponse([
                    'status' => 'error',
                    'message' => 'Registration rejected.'
                ], Response::HTTP_FORBIDDEN);
            }

            $this->logger->info('Registration callback completed successfully', [
                'email_hash' => LogTrace::fingerprint($dto->getEmail()),
                'public_id_hash' => LogTrace::fingerprint($dto->getPublicId()),
                'process_hash' => LogTrace::fingerprint($dto->getProcessId()),
            ]);

            return new JsonResponse(['status' => 'success', 'data' => 'callback success'], Response::HTTP_OK);
        } catch (BadRequestHttpException $e) {
            $this->logger->error('Registration callback request handling failed', [
                'error' => $e->getMessage(),
            ]);

            return new JsonResponse([
                'status' => 'error',
                'message' => $e->getMessage()
            ], Response::HTTP_BAD_REQUEST);
        } catch (\Exception $e) {
            $this->logger->error('Registration callback request handling failed', [
                'error' => $e->getMessage(),
            ]);

            return new JsonResponse([
                'status' => 'error',
                'message' => 'Internal Server Error'
            ], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }
}
