<?php

/**
 * Credential Hub - One Touch Authentication module: handles QR-based one-touch authentication for browser extensions
 * 1. QR Identity Generation general process creation
 * 2. Read the Mobile Apps QR code and confirm the identifier with the call from the mobile app for one-touch authentication.
 * 3. Polling for one-touch authentication state => UserPublicId and E-mail stored on the client side  (Browser Extension))
 */

namespace App\Controller\CredentialHub\OneTouch;

use App\Attribute\ExtensionAuthRequired;
use App\Attribute\PublicRoute;
use App\Controller\Shared\AbstractBackendForwardingController;
use App\Service\Shared\ProcessKey;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\User\BackendForwardingService;
use Symfony\Component\HttpFoundation\JsonResponse;
use Psr\Log\LoggerInterface;

#[Route('/api/credential-hub/one-touch')]
class OneTouchController extends AbstractBackendForwardingController
{
    public function __construct(
        private LoggerInterface $logger
    ) {
    }


    /*
     * API endpoint for QR-based one-touch authentication (called by Browser-Extension).
     * Receives QR identity data, forwards it to the backend API for one-touch session initialization.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[PublicRoute('Public Credential Hub bootstrap route that creates the one-touch process and returns the initial QR/session payload.')]
    #[Route('/qr-identity', name: ProcessKey::ONE_TOUCH_QR_IDENTITY, methods: "POST")]
    public function oneTouchQrIdentity(
        Request $request,
        BackendForwardingService $backendForwardingService
    ): JsonResponse {
        return $this->forwardProcessRequest($request, $backendForwardingService, $this->logger, ProcessKey::ONE_TOUCH_QR_IDENTITY);
    }

    /*
     * API endpoint for one-touch identifier confirmation (called by Mobile App).
     * The QR code generated by the first method is scanned by the mobile app, which sends a confirmation to this endpoint.
     * This endpoint forwards the confirmation request and extension auth header to the backend API for one-touch authentication.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[ExtensionAuthRequired('One-touch confirmation requests must include the X-Extension-Auth header established by the bootstrap step.')]
    #[Route('/identifier', name: ProcessKey::ONE_TOUCH_IDENTIFIER, methods: "POST")]
    public function oneTouchIdentifier(
        Request $request,
        BackendForwardingService $backendForwardingService
    ): JsonResponse {
        return $this->forwardProcessRequest($request, $backendForwardingService, $this->logger, ProcessKey::ONE_TOUCH_IDENTIFIER);
    }

    /*
     * API endpoint for one-touch authentication state polling (called by Browser-Extension).
     * Receives state request data and extension auth header, forwards to backend API.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[ExtensionAuthRequired('One-touch state polling must include the X-Extension-Auth header established by the bootstrap step.')]
    #[Route('/state', name: ProcessKey::ONE_TOUCH_STATE, methods: "POST")]
    public function oneTouchState(
        BackendForwardingService $backendForwardingService,
        Request $request
    ): JsonResponse {
        return $this->forwardProcessRequest($request, $backendForwardingService, $this->logger, ProcessKey::ONE_TOUCH_STATE);
    }
}
