<?php

/**
 * Credential Hub - One Touch Authentication module: handles QR-based one-touch authentication for browser extensions 
 * 1. QR Identity Generation general process creation
 * 2. Read the Mobile Apps QR code and confirm the identifier with the call from the mobile app for one-touch authentication.
 * 3. Polling for one-touch authentication state => UserPublicId and E-mail stored on the client side  (Browser Extension))
 */ 
namespace App\Controller\CredentialHub\OneTouch;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\User\UserRegistrationService;
use Symfony\Component\HttpFoundation\JsonResponse;
use Psr\Log\LoggerInterface;


#[Route('/api/credential-hub/one-touch')]
class OneTouchController extends AbstractController
{
    public function __construct(
        private LoggerInterface $logger
    ) {}


    /*
     * API endpoint for QR-based one-touch authentication (called by Browser-Extension).
     * Receives QR identity data, forwards it to the backend API for one-touch session initialization.
     * Uses UserRegistrationService->forwardRegistration, which encrypts and sends data to backend API.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[Route('/qr-identity', name: 'one_touch_qr_identity', methods: "POST")]
    public function oneTouchQrIdentity(
        Request $request,
        UserRegistrationService $userRegistrationService
    ): JsonResponse {
        $contentJson = $request->getContent();
        $process = "one_touch_qr_identity";

        /** @var Response $response */
        $response = $userRegistrationService->forwardRegistration(
            [$process => json_decode($contentJson)]
        );

        $content = $response->getContent();
        $decodedJson = \json_decode($content);
        
        return $this->json($decodedJson);
    }

    /*
     * API endpoint for one-touch identifier confirmation (called by Mobile App).
     * The QR code generated by the first method is scanned by the mobile app, which sends a confirmation to this endpoint.
     * This endpoint forwards the confirmation request and extension auth header to the backend API for one-touch authentication.
     * Uses UserRegistrationService->forwardRegistration, which encrypts and sends data to backend API.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[Route('/identifier', name: 'one_touch_identifier', methods: "POST")]
    public function domainReadCredential(
        Request $request,
        UserRegistrationService $userRegistrationService
    ): JsonResponse {
        $contentJson = $request->getContent();

        $process = "one_touch_identifier";

        /** @var Response $response */
        $response = $userRegistrationService->forwardRegistration(
            [
                $process => json_decode($contentJson),
                'X-Extension-Auth' => $request->headers->get('X-Extension-Auth')
                ]
        );

        $content = $response->getContent();
        $decodedJson = \json_decode($content);
        
        return $this->json($decodedJson);
    }

    /*
     * API endpoint for one-touch authentication state polling (called by Browser-Extension).
     * Receives state request data and extension auth header, forwards to backend API.
     * Uses UserRegistrationService->forwardRegistration, which encrypts and sends data to backend API.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[Route('/state', name: 'one_touch_state', methods: "POST")]
    public function oneTouchState(
        UserRegistrationService $userRegistrationService,
        Request $request
    ): JsonResponse {
        $contentJson = $request->getContent();
        $process = "one_touch_state";

        /** @var Response $response */
        $response = $userRegistrationService->forwardRegistration(
            [
                $process => $contentJson,
                'X-Extension-Auth' => $request->headers->get('X-Extension-Auth')
            ]
        );

        $content = $response->getContent();
        $decodedJson = \json_decode($content);
       
        
       return new JsonResponse($decodedJson);
    }
}
