<?php
/**
 * Registration flow:
 * 1. Generate a QR code included the credentials.
 * 2. Read the QR code with the mobile application, which encrypts the credentials and sends a confirmation back to the API /new endpoint.
 * 3. Use the /state endpoint to deliver the process status.
 */
namespace App\Controller\CredentialHub\Shared;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\User\UserRegistrationService;
use Symfony\Component\HttpFoundation\JsonResponse;
use Psr\Log\LoggerInterface;
use App\Controller\CredentialHub\BackendForwared;

#[Route('/api/credential-hub/shared/registration')]
class RegistrationController extends AbstractController
{
    public function __construct(
        private LoggerInterface $logger
    ) {}

    /*
     * API endpoint for QR-based shared registration (called by Browser-Extension).
     * Receives QR identity data, forwards it to the Browser-Extension. Only initial step to get the sessionId.
     * Uses UserRegistrationService->forwardRegistration, which encrypts and sends data to backend API.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[Route('/qr-identity', name: 'shared_registration_qr_identity', methods: "POST")]
    public function sharedRegistrationQrIdentity(
        Request $request,
        UserRegistrationService $userRegistrationService
    ): JsonResponse {
        return BackendForwared::forward($request, $userRegistrationService, $this->logger, 'shared_registration_qr_identity');
    }

    /*
     * API endpoint for shared registration confirmation (called by Mobile App).
     * The QR code generated by the first method is scanned by the mobile app, which sends a confirmation 
     * and the encrypted credentials to this endpoint.
     * This endpoint forwards the confirmation request and extension auth header to the backend API for registration.
     * Uses UserRegistrationService->forwardRegistration, which encrypts and sends data to backend API.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[Route('/new', name: 'shared_registration_new', methods: "POST")]
    public function sharedRegistrationNew(
        Request $request,
        UserRegistrationService $userRegistrationService
    ): JsonResponse {
        return BackendForwared::forward($request, $userRegistrationService, $this->logger, 'shared_registration_new', true);
    }

    /*
     * API endpoint for shared registration state polling (called by Browser-Extension).
     * Receives state request data and extension auth header, forwards to backend API.
     * Uses UserRegistrationService->forwardRegistration, which encrypts and sends data to backend API.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[Route('/state', name: 'shared_registration_state', methods: "POST")]
    public function sharedRegistrationState(
        Request $request,
        UserRegistrationService $userRegistrationService
    ): JsonResponse {
        $contentJson = $request->getContent();
        $process = "shared_registration_state";
        return BackendForwared::forward($request, $userRegistrationService, $this->logger, 'shared_registration_state', true);
    }
}