<?php

/**
 * Registration flow:
 * 1. Generate a QR code included the credentials.
 * 2. Read the QR code with the mobile application, which encrypts the credentials and sends a confirmation back to the API /new endpoint.
 * 3. Use the /state endpoint to deliver the process status.
 */

namespace App\Controller\CredentialHub\Shared;

use App\Attribute\ExtensionAuthRequired;
use App\Attribute\PublicRoute;
use App\Controller\Shared\AbstractBackendForwardingController;
use App\Service\Shared\ProcessKey;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\User\BackendForwardingService;
use Symfony\Component\HttpFoundation\JsonResponse;
use Psr\Log\LoggerInterface;

#[Route('/api/credential-hub/shared/registration')]
class RegistrationController extends AbstractBackendForwardingController
{
    public function __construct(
        private LoggerInterface $logger
    ) {
    }

    /*
     * API endpoint for QR-based shared registration (called by Browser-Extension).
     * Receives QR identity data, forwards it to the Browser-Extension. Only initial step to get the sessionId.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[PublicRoute('Public Credential Hub bootstrap route that creates the shared-registration process and returns the initial QR/session payload.')]
    #[Route('/qr-identity', name: ProcessKey::SHARED_REGISTRATION_QR_IDENTITY, methods: "POST")]
    public function sharedRegistrationQrIdentity(
        Request $request,
        BackendForwardingService $backendForwardingService
    ): JsonResponse {
        return $this->forwardProcessRequest($request, $backendForwardingService, $this->logger, ProcessKey::SHARED_REGISTRATION_QR_IDENTITY);
    }

    /*
     * API endpoint for shared registration confirmation (called by Mobile App).
    * The QR code generated by the first method is scanned by the mobile app, which sends a request to retrieve the
     * credentials and encrypt them on the mobile app.
     * Then the mobile app sends a confirmation and the encrypted credentials to the /new endpoint.
     * This endpoint forwards the confirmation request and extension auth header to the backend API for registration.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[ExtensionAuthRequired('Shared-registration encryption preparation must include the X-Extension-Auth header established by the bootstrap step.')]
    #[Route('/new/to-encrypt', name: ProcessKey::SHARED_REGISTRATION_NEW_TO_ENCRYPT, methods: "POST")]
    public function sharedRegistrationNewToEncrypt(
        Request $request,
        BackendForwardingService $backendForwardingService
    ): JsonResponse {
        return $this->forwardProcessRequest($request, $backendForwardingService, $this->logger, ProcessKey::SHARED_REGISTRATION_NEW_TO_ENCRYPT);
    }

    /*
     * API endpoint for shared registration confirmation (called by Mobile App).
     * The QR code generated by the first method is scanned by the mobile app, which sends a confirmation
     * and the encrypted credentials to this endpoint.
     * This endpoint forwards the confirmation request and extension auth header to the backend API for registration.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[ExtensionAuthRequired('Shared-registration confirmation must include the X-Extension-Auth header established by the bootstrap step.')]
    #[Route('/new', name: ProcessKey::SHARED_REGISTRATION_NEW, methods: "POST")]
    public function sharedRegistrationNew(
        Request $request,
        BackendForwardingService $backendForwardingService
    ): JsonResponse {
        return $this->forwardProcessRequest($request, $backendForwardingService, $this->logger, ProcessKey::SHARED_REGISTRATION_NEW);
    }

    /*
     * API endpoint for shared registration state polling (called by Browser-Extension).
     * Receives state request data and extension auth header, forwards to backend API.
     * Tries to decode backend response as JSON and returns it; if not valid JSON, result may be null or incomplete.
     */
    #[ExtensionAuthRequired('Shared-registration state polling must include the X-Extension-Auth header established by the bootstrap step.')]
    #[Route('/state', name: ProcessKey::SHARED_REGISTRATION_STATE, methods: "POST")]
    public function sharedRegistrationState(
        Request $request,
        BackendForwardingService $backendForwardingService
    ): JsonResponse {
        return $this->forwardProcessRequest($request, $backendForwardingService, $this->logger, ProcessKey::SHARED_REGISTRATION_STATE);
    }
}
